version: '3.9'

services:
  web:
    build: .
    command: 
      - sh 
      - -c 
      - |
        while ! nc -z db 5432;
        do
          echo 'Aguardando o banco de dados...';
          sleep 1;
        done;
        python manage.py migrate;
        python manage.py collectstatic --no-input;
        python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - PG_HOST=db
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=movie_db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: